version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678     
      POSTGRES_DB: sysmon   
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      [db]

volumes:
  pgdata: